country: China
province: beijing
city: beijing
area: haidian

user:
  -
    name: cuiwei
    age: 21

likes:
  - game
  - music
  - woman

datasource:
  driver: com.mysql.jdbc.Driver
  url: loclalhost://///
  username: root
  password: 123456

  #端口配置
server:
  port: 80