servers:
             ipAddress: 192.168.0.1
             port: 1111
             timeout: -1
             serverTimeOut: 3
             dataSize: 1024

datasource:
                    driverClassName: com.mysql.jdbc.Driver123555
                    password: 0127