server:
  port: 80

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb1_
      id-type: auto
      cofiguration:
          log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db
    username: root
    password: 123456
  main:
    allow-circular-references: true
jetcache:
  statIntervalMinutes: 1
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      host: localhost
      port: 6379
      keyConvertor: fastjson
      valueEncode: java
      valueDecode: java
      poolConfig:
        maxTotal: 50
  sms:
    type: redis
    host: localhost
    port: 6379
    poolConfig:
      maxTotal: 50






















